name: jupyterlite-dev
# this is a conda/mamba environment for working on JupyterLite and upstreams

channels:
  - conda-forge

dependencies:
  # build stuff
  - black
  - depfinder
  - isort
  - pyflakes
  - twine
  # demo stuff
  - jupyter-server-proxy
  - jupyterlab >=3.4.2,<4
  - retrolab >=0.3.21,<0.4
  # extra docs tools
  - sphinx-autobuild

  # the chunk below populates `../examples/jupyter_lite_config.json`,
  # rewriting `anaconda.org` links to `conda-forge`'s GitHub releases
  ### FEDERATED EXTENSIONS ###
  - jupyterlab_miami_nights
  - jupyterlab_widgets >=1,<2
  - jupyterlab-drawio
  - jupyterlab-fasta >=3,<4
  - jupyterlab-geojson >=3,<4
  - jupyterlab-kernelspy
  - jupyterlab-markup
  - jupyterlab-myst
  - jupyterlab-tour >=3.1.0
  - jupyterlab-webrtc-docprovider >=0.1.1
  - theme-darcula >=3,<4
  # if a package is pinned with == `doit check` will ensure the version is pinned
  # in `docs/_build/_static/files/*.ipynb`
  - bqplot
  - ipycanvas
  - ipycytoscape
  - ipyleaflet
  - ipympl
  - ipyvue
  - ipyvuetify
  - plotly
  ### FEDERATED EXTENSIONS ###

  # the chunk below gets copied from `../docs/environment.yml` by `doit env`
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.9,<3.10
  # build
  - doit >=0.33,<0.34
  - flit >=3.7.1,<4
  - jupyter-server-mathjax >=0.2.3
  - jsonschema >=3
  - pip
  - pkginfo
  - requests_cache
  - wheel
  - yarn <2
  # cli
  - wheel
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # language packs and contents
  - jupyter_server >=1.11,<2
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab_server >=2.8.1,<3
  ### DOCS ENV ###
